// components/DecoratorsToTypesSection.tsx
import styles from './home-page.module.scss';
import CodeBlock from '@theme/CodeBlock';

const DecoratorsToTypesSection = () => (
  <section className={`${styles.section} ${styles['section--decorators-to-types']}`}>
    <div className={styles['hero__container']}>
      <div className={styles['section__header']}>
        <h2 className={styles['section__title']}>From Decorators to Types</h2>
        <p className={styles['section__description']}>
          Decorate your backend, get clean type definitions. No runtime code, no bundle bloat.
        </p>
      </div>
      <div className={styles['code-grid']}>
        <div className={styles['code-block']}>
            <CodeBlock language='typescript' title="Backend Controller with Decorators">
            {`import { ApinniController, ApinniEndpoint } from 'apinni';

type CreateUserDto = {
  name: string;
  email: string;
}

@ApinniController({ path: '/api/users' })
export class UserController {
  @ApinniEndpoint({ path: '/:id', method: 'GET' })
  async getUserById() {
    // your framework specific param resolver
    return { id: '1', name: 'John', email: 'john@mail.com' };
  }

  @ApinniEndpoint<{
    request: { 
      type: CreateUserDto 
    }
  }>({ path: '/', method: 'POST' })
  async createUser(userData: CreateUserDto) {
    return {
      id: '1',
      ...userData,
      createdAt: new Date().toISOString()
    };
  }
}`}
            </CodeBlock>
        </div>
        <div className={styles['code-block']}>
            <CodeBlock language='typescript' title="Generated types.d.ts File">
            {`// Auto-generated by Apinni - Never bundled
export type GetApiUsersByIdResponse = {
  id: string;
  name: string;
  email: string;
};

export type CreateUserDto = {
  name: string;
  email: string;
}

export type PostApiUsersRequest = CreateUserDto

export type PostApiUsersResponse = {
  id: string;
  name: string;
  email: string;
  createdAt: string;
};

// API Schema - No runtime code
export type Api = BuildApi<{
  ['/api/users/:id']: {
    GET: {
      query: never;
      request: never;
      responses: {
        200: GetApiUsersByIdResponse;
      };
    };
  };
  ['/api/users']: {
    POST: {
      query: never;
      request: PostApiUsersRequest;
      responses: {
        200: PostApiUsersResponse;
      };
    };
  };
}>;

// Utilities goes here`}
            </CodeBlock>
        </div>
      </div>
    </div>
  </section>
);

export default DecoratorsToTypesSection;